### ISSUE TITLE
Pазве сущности могут импортировать друг друга?

### ISSUE THREAD

**Issue by usmanyunusov** [noveogroup-amorgunov/nukeapp#5]
https://github.com/noveogroup-amorgunov/nukeapp/blob/81426c2841e230bd376834c80bb3ac985862a61a/src/entities/category/lib/mapCategoryWithProducts.ts#LL1C1-L1C1

**Comment by noveogroup-amorgunov** [comment]
@usmanyunusov привет! В проекте используется экспериментальная фича FSD, которые разрешает кросс импорты в сущностях через специальное API. Подробнее здесь: https://github.com/feature-sliced/documentation/discussions/390#discussioncomment-5570073 т.е. мы создаем специальный файл с публичным API именно для связанной сущности (пример из проекта: https://github.com/noveogroup-amorgunov/nukeapp/blob/81426c2841e230bd376834c80bb3ac985862a61a/src/entities/product/%40x/category.ts)

Объекты в реальном мире взаимодействуют, таблицы в базах данных связаны, сущности в FSD - не исключение. Писать реальное приложение и исключить импорты сущностей друг с другом на проектах больше маленького либо невозможно, либо нужно написать огромное количество абстракций, чтобы следовать методологии. Поэтому я думаю дело времени, пока в FSD не появится стабильный механизм, как сушности смогут взаимодействовать друг с другом
